### ISSUE TITLE
ufw port 8080 allow should be based of of .conf variable value

### ISSUE THREAD

**Issue by BenGardiner** [reap3r/nmfta-bouncer#15]
https://github.com/reap3r/firewall/blob/82cdd5a3455fa5d72630ecdabefba705507d84b4/appliance/src/rules_scheduler.py#L51

if the .conf variable is set to something other than 8080 then the firewall will block traffic to the webserver and someone will have a bad day.

Follow-on issue: as you add reading of the .conf file, you will need to ensure that it cannot have been modified by a lower privilege before opening it since that file will be anotehr vector into this most-privileged domain of executing firewall rules ... as root

**Comment by reap3r** [comment]
Rules now reads from the conf file
