### ISSUE TITLE
secrets need to be in secret data files

### ISSUE THREAD

**Issue by BenGardiner** [reap3r/nmfta-bouncer#3]
c.f. https://github.com/reap3r/firewall/blob/master/appliance/app/rest_interface.py#L16 and https://github.com/reap3r/firewall/blob/master/appliance/app/rest_interface.py#L19

Your comments there are correct. These need to be changed and stored outside the repo code. Load them from a data file, but do so much like .ssh priv keys: test that the file is readable only by the user running the service. Fail early otherwise.

**Comment by reap3r** [comment]
JWT "secrets" are no longer stored statically. Instead, they are randomly generated whenever the server starts.
